### ISSUE TITLE
VS 2017 Support?

### ISSUE THREAD

**Issue by StevenGann** [EgorBo/Disasmo#1]
This looks amazing, and I don't know why I've never seen it done before.
Unfortunately, I'm stuck in ancient history with Visual Studio 2017.

Is 2017 support possible, and if so would you be willing to add support? I'd be willing to recompile it myself, but I'm willing to bet there's others who would appreciate it too.

**Comment by EgorBo** [comment]
Hm.. tried to run under VS2017 - the main DisasmoPackage loads fine and breakpoins work but the Light Bulb stuff doesn't for some reason...

**Comment by Mitiko** [comment]
And what about VSCode?

**Comment by StevenGann** [comment]
AFAIK, VS Code extensions are written in JavaScript, so porting it would be a total rewrite.
