### ISSUE TITLE
Doesn't work in projects without entry point method

### ISSUE THREAD

**Issue by kindermannhubert** [EgorBo/Disasmo#12]
This is expected from the way how it works now (injecting some code to Main method and then running the executable).
I propose having simple "runner" executable (distributed along side with Disasmo) which would accept arguments telling it which dll/exe to load and which type/methods to prepare (=be JITed). Then there would be no need for code injection used now and it would be possible to disasm even methods from dlls.
It would also solve #3.

I can prepare pull request if you agree.

**Comment by EgorBo** [comment]
Thanks for the suggestion, it already works as you described
