### ISSUE TITLE
Disassembly does not work if AssemblyName != ProjectName

### ISSUE THREAD

**Issue by rickbrew** [EgorBo/Disasmo#35]
There's a `TODO` in the code for this: https://github.com/EgorBo/Disasmo/blob/38e26cdb1496c3c3d4b196c2d5c0ffd7329f9a8a/src/Vsix/ViewModels/MainViewModel.cs#L169

This affects me with Paint.NET because all of the assembly names are prefixed with `PaintDotNet`, but the project names are not, e.g. `Primitives.csproj` / `PaintDotNet.Primitives.dll`

**Comment by EgorBo** [comment]
Fixed 🙂
