### ISSUE TITLE
Feature Request: Add a define when compiling

### ISSUE THREAD

**Issue by TJHeuvel** [EgorBo/Disasmo#49]
I have a test app that runs DotNetBenchmark when building with Release, and some testing when ran in DEBUG.

I'd also really like Disasmo to run the debug case, but without actually compiling debug. I think this can be done by having Disamo adding a new define, so i can do:

```
#if DEBUG || DISASMO
//a
#else
//b
#endif
```

**Comment by EgorBo** [comment]
Thanks, good idea, added
