### ISSUE TITLE
NullReferenceException in ObjectLayoutSuggestedAction.GetSymbol

### ISSUE THREAD

**Issue by sharwell** [EgorBo/Disasmo#5]
After reviewing data submitted by a user in [Executing View.QuickActions often throws an exception](https://developercommunity.visualstudio.com/content/problem/474340/executing-viewquickactions-often-throws-an-excepti.html), I found it's possible for a `NullReferenceException` to be thrown in `ObjectLayoutSuggestedAction.GetSymbol`, which eventually propagates to `CommonSuggestedActionsSource.HasSuggestedActionsAsync`. This unhandled exception causes the lightbulb to misbehave. The following screenshot shows the problematic call stack:

![image](https://user-images.githubusercontent.com/1408396/53977654-1e2a3000-40cf-11e9-82d5-d923518504fb.png)

**Comment by EgorBo** [comment]
@sharwell wow, thanks!! will fix

**Comment by sharwell** [comment]
@EgorBo No problem. I was happy to find that the extension was open source so I could get the info to you 👍
